// Generated by gir (https://github.com/gtk-rs/gir @ 5c82e8f762bf)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 68003b4b40e5)
// DO NOT EDIT

#[cfg(not(feature = "dox"))]
use std::process;

#[cfg(feature = "dox")]
fn main() {} // prevent linking libraries to avoid documentation failure

#[cfg(not(feature = "dox"))]
fn main() {
    if let Err(s) = system_deps::Config::new().probe() {
        println!("cargo:warning={}", s);
        process::exit(1);
    }
}
