// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

use glib::object::Cast;
use glib::object::IsA;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    pub struct ApplicationWindow(Object<ffi::AdwApplicationWindow, ffi::AdwApplicationWindowClass>) @extends gtk::ApplicationWindow, gtk::Window, gtk::Widget, @implements gtk::Accessible, gtk::Buildable, gtk::ConstraintTarget, gtk::Native, gtk::Root, gtk::ShortcutManager, gio::ActionGroup, gio::ActionMap;

    match fn {
        get_type => || ffi::adw_application_window_get_type(),
    }
}

impl ApplicationWindow {
    #[doc(alias = "adw_application_window_new")]
    pub fn new<P: IsA<gtk::Application>>(app: &P) -> ApplicationWindow {
        assert_initialized_main_thread!();
        unsafe {
            gtk::Widget::from_glib_full(ffi::adw_application_window_new(
                app.as_ref().to_glib_none().0,
            ))
            .unsafe_cast()
        }
    }
}

pub const NONE_APPLICATION_WINDOW: Option<&ApplicationWindow> = None;

pub trait ApplicationWindowExt: 'static {
    #[doc(alias = "adw_application_window_get_child")]
    fn child(&self) -> Option<gtk::Widget>;

    #[doc(alias = "adw_application_window_set_child")]
    fn set_child<P: IsA<gtk::Widget>>(&self, child: Option<&P>);
}

impl<O: IsA<ApplicationWindow>> ApplicationWindowExt for O {
    fn child(&self) -> Option<gtk::Widget> {
        unsafe {
            from_glib_none(ffi::adw_application_window_get_child(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    fn set_child<P: IsA<gtk::Widget>>(&self, child: Option<&P>) {
        unsafe {
            ffi::adw_application_window_set_child(
                self.as_ref().to_glib_none().0,
                child.map(|p| p.as_ref()).to_glib_none().0,
            );
        }
    }
}

impl fmt::Display for ApplicationWindow {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("ApplicationWindow")
    }
}
