// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

use std::ffi::CStr;

#[doc(alias = "ADW_VERSION_S")]
pub static VERSION_S: once_cell::sync::Lazy<&'static str> =
    once_cell::sync::Lazy::new(|| unsafe { CStr::from_ptr(ffi::ADW_VERSION_S).to_str().unwrap() });
