// Generated by gir (https://github.com/gtk-rs/gir @ 1bef39f)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 6088bb6)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "AdwActionRow", sizeof(AdwActionRow), alignof(AdwActionRow));
    printf("%s;%zu;%zu\n", "AdwActionRowClass", sizeof(AdwActionRowClass), alignof(AdwActionRowClass));
    printf("%s;%zu;%zu\n", "AdwApplicationWindow", sizeof(AdwApplicationWindow), alignof(AdwApplicationWindow));
    printf("%s;%zu;%zu\n", "AdwApplicationWindowClass", sizeof(AdwApplicationWindowClass), alignof(AdwApplicationWindowClass));
    printf("%s;%zu;%zu\n", "AdwAvatarClass", sizeof(AdwAvatarClass), alignof(AdwAvatarClass));
    printf("%s;%zu;%zu\n", "AdwBin", sizeof(AdwBin), alignof(AdwBin));
    printf("%s;%zu;%zu\n", "AdwBinClass", sizeof(AdwBinClass), alignof(AdwBinClass));
    printf("%s;%zu;%zu\n", "AdwCarouselClass", sizeof(AdwCarouselClass), alignof(AdwCarouselClass));
    printf("%s;%zu;%zu\n", "AdwCarouselIndicatorDotsClass", sizeof(AdwCarouselIndicatorDotsClass), alignof(AdwCarouselIndicatorDotsClass));
    printf("%s;%zu;%zu\n", "AdwCarouselIndicatorLinesClass", sizeof(AdwCarouselIndicatorLinesClass), alignof(AdwCarouselIndicatorLinesClass));
    printf("%s;%zu;%zu\n", "AdwCenteringPolicy", sizeof(AdwCenteringPolicy), alignof(AdwCenteringPolicy));
    printf("%s;%zu;%zu\n", "AdwClampClass", sizeof(AdwClampClass), alignof(AdwClampClass));
    printf("%s;%zu;%zu\n", "AdwClampLayoutClass", sizeof(AdwClampLayoutClass), alignof(AdwClampLayoutClass));
    printf("%s;%zu;%zu\n", "AdwClampScrollableClass", sizeof(AdwClampScrollableClass), alignof(AdwClampScrollableClass));
    printf("%s;%zu;%zu\n", "AdwComboRow", sizeof(AdwComboRow), alignof(AdwComboRow));
    printf("%s;%zu;%zu\n", "AdwComboRowClass", sizeof(AdwComboRowClass), alignof(AdwComboRowClass));
    printf("%s;%zu;%zu\n", "AdwEnumListModelClass", sizeof(AdwEnumListModelClass), alignof(AdwEnumListModelClass));
    printf("%s;%zu;%zu\n", "AdwEnumValueObjectClass", sizeof(AdwEnumValueObjectClass), alignof(AdwEnumValueObjectClass));
    printf("%s;%zu;%zu\n", "AdwExpanderRow", sizeof(AdwExpanderRow), alignof(AdwExpanderRow));
    printf("%s;%zu;%zu\n", "AdwExpanderRowClass", sizeof(AdwExpanderRowClass), alignof(AdwExpanderRowClass));
    printf("%s;%zu;%zu\n", "AdwFlapClass", sizeof(AdwFlapClass), alignof(AdwFlapClass));
    printf("%s;%zu;%zu\n", "AdwFlapFoldPolicy", sizeof(AdwFlapFoldPolicy), alignof(AdwFlapFoldPolicy));
    printf("%s;%zu;%zu\n", "AdwFlapTransitionType", sizeof(AdwFlapTransitionType), alignof(AdwFlapTransitionType));
    printf("%s;%zu;%zu\n", "AdwHeaderBarClass", sizeof(AdwHeaderBarClass), alignof(AdwHeaderBarClass));
    printf("%s;%zu;%zu\n", "AdwLeafletClass", sizeof(AdwLeafletClass), alignof(AdwLeafletClass));
    printf("%s;%zu;%zu\n", "AdwLeafletPageClass", sizeof(AdwLeafletPageClass), alignof(AdwLeafletPageClass));
    printf("%s;%zu;%zu\n", "AdwLeafletTransitionType", sizeof(AdwLeafletTransitionType), alignof(AdwLeafletTransitionType));
    printf("%s;%zu;%zu\n", "AdwNavigationDirection", sizeof(AdwNavigationDirection), alignof(AdwNavigationDirection));
    printf("%s;%zu;%zu\n", "AdwPreferencesGroup", sizeof(AdwPreferencesGroup), alignof(AdwPreferencesGroup));
    printf("%s;%zu;%zu\n", "AdwPreferencesGroupClass", sizeof(AdwPreferencesGroupClass), alignof(AdwPreferencesGroupClass));
    printf("%s;%zu;%zu\n", "AdwPreferencesPage", sizeof(AdwPreferencesPage), alignof(AdwPreferencesPage));
    printf("%s;%zu;%zu\n", "AdwPreferencesPageClass", sizeof(AdwPreferencesPageClass), alignof(AdwPreferencesPageClass));
    printf("%s;%zu;%zu\n", "AdwPreferencesRow", sizeof(AdwPreferencesRow), alignof(AdwPreferencesRow));
    printf("%s;%zu;%zu\n", "AdwPreferencesRowClass", sizeof(AdwPreferencesRowClass), alignof(AdwPreferencesRowClass));
    printf("%s;%zu;%zu\n", "AdwPreferencesWindow", sizeof(AdwPreferencesWindow), alignof(AdwPreferencesWindow));
    printf("%s;%zu;%zu\n", "AdwPreferencesWindowClass", sizeof(AdwPreferencesWindowClass), alignof(AdwPreferencesWindowClass));
    printf("%s;%zu;%zu\n", "AdwSqueezerClass", sizeof(AdwSqueezerClass), alignof(AdwSqueezerClass));
    printf("%s;%zu;%zu\n", "AdwSqueezerPageClass", sizeof(AdwSqueezerPageClass), alignof(AdwSqueezerPageClass));
    printf("%s;%zu;%zu\n", "AdwSqueezerTransitionType", sizeof(AdwSqueezerTransitionType), alignof(AdwSqueezerTransitionType));
    printf("%s;%zu;%zu\n", "AdwStatusPageClass", sizeof(AdwStatusPageClass), alignof(AdwStatusPageClass));
    printf("%s;%zu;%zu\n", "AdwSwipeTrackerClass", sizeof(AdwSwipeTrackerClass), alignof(AdwSwipeTrackerClass));
    printf("%s;%zu;%zu\n", "AdwSwipeableInterface", sizeof(AdwSwipeableInterface), alignof(AdwSwipeableInterface));
    printf("%s;%zu;%zu\n", "AdwTabBarClass", sizeof(AdwTabBarClass), alignof(AdwTabBarClass));
    printf("%s;%zu;%zu\n", "AdwTabPageClass", sizeof(AdwTabPageClass), alignof(AdwTabPageClass));
    printf("%s;%zu;%zu\n", "AdwTabViewClass", sizeof(AdwTabViewClass), alignof(AdwTabViewClass));
    printf("%s;%zu;%zu\n", "AdwValueObjectClass", sizeof(AdwValueObjectClass), alignof(AdwValueObjectClass));
    printf("%s;%zu;%zu\n", "AdwViewSwitcherBarClass", sizeof(AdwViewSwitcherBarClass), alignof(AdwViewSwitcherBarClass));
    printf("%s;%zu;%zu\n", "AdwViewSwitcherClass", sizeof(AdwViewSwitcherClass), alignof(AdwViewSwitcherClass));
    printf("%s;%zu;%zu\n", "AdwViewSwitcherPolicy", sizeof(AdwViewSwitcherPolicy), alignof(AdwViewSwitcherPolicy));
    printf("%s;%zu;%zu\n", "AdwViewSwitcherTitleClass", sizeof(AdwViewSwitcherTitleClass), alignof(AdwViewSwitcherTitleClass));
    printf("%s;%zu;%zu\n", "AdwWindow", sizeof(AdwWindow), alignof(AdwWindow));
    printf("%s;%zu;%zu\n", "AdwWindowClass", sizeof(AdwWindowClass), alignof(AdwWindowClass));
    printf("%s;%zu;%zu\n", "AdwWindowTitleClass", sizeof(AdwWindowTitleClass), alignof(AdwWindowTitleClass));
    return 0;
}
